<!-- Nav (menu) -->
<nav id="primary_nav">
    <ul>
        <li><a href="../../index.php">Accueil</a></li>
        <li><a href="../../listeDestinations.php">Destinations</a></li>
        <li><a href="../../voeux.php">Faire ses voeux</a></li>
        <li><a href="../../contact.php">Contact</a></li>
        <?php if (isset($_SESSION['login']) && isset($_SESSION['pwd'])) : ?>
            <li><a href="../../deconnexion.php">Deconnexion</a></li>
        <?php else : ?>
            <li><a href="../../connexion.php">Admin</a></li>
        <?php endif; ?>
        <li class="top"><a href="#home">Haut</a></li>
    </ul>
</nav><!--end primary_nav-->