<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity | Connexion</title>
    <meta name="description" content="Page de connexion à l'administrateur">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!-- css -->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>
    <script src="../js/jquery-validation1.17.0.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <h4>Connexion Admin Page</h4>

        <?php if (!empty($error_msg)) :?>
        <div id="error">
            <!-- error will be shown here ! -->
            <div class="alert">
                <span class="closebtn">&times;</span>
                <p><b>Erreur ! </b><?= $error_msg ?></p>
            </div>
        </div>
        <?php endif; ?>

        <form action="../controleurs/ControllerConnexion.php" method="post">
            <label for="login">Votre login : </label>
            <input type="text" name="login" id="login" >
            <label for="pwd">Votre mot de passé : </label>
            <input type="password" name="pwd" id="pwd">
            <input type="submit" id="submit" value="Connexion">
        </form>

        <p>Work In Progress</p>
    </div><!--container-->

    <?php include('Defaut/menu.phtml'); ?>

    <?php include('Defaut/footer.phtml'); ?>

    <script src="../js/connexion.js"></script>
    <script src="../js/alert-box.js"></script>
</div><!--end wrapper-->

</body>
</html>