<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity | Connexion</title>
    <meta name="description" content="Page de connexion à l'administrateur">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!-- css -->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>
    <script src="../js/jquery-validation1.17.0.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <h2>ADMINISTRATION</h2>

        <?php if (!empty($error_msg)) :?>
        <div id="error">
            <!-- error will be shown here ! -->
            <div class="alert">
                <span class="closebtn">&times;</span>
                <p><b>Erreur ! </b><?= $error_msg ?></p>
            </div>
        </div>
        <?php endif; ?>
        <div class="adminForm">
            <form action="../controleurs/ControllerConnexion.php" method="post">
                <table>
                    <tr>
                        <td><label for="login">Login : </label></td><td><input type="text" name="login" id="login" ></td>
                    </tr>
                    <tr>
                        <td><label for="pwd">Mot de passe : </label></td><td><input type="password" name="pwd" id="pwd"></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" id="submit" value="Connexion"></td>
                    </tr>
                </table>
            </form>
        </div><!--adminForm-->
    </div><!--container-->
<br /><br />
    <?php include('Defaut/footer.phtml'); ?>

    <script src="../js/connexion.js"></script>
    <script src="../js/alert-box.js"></script>
</div><!--end wrapper-->

</body>
</html>