<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity | Contact</title>
    <meta name="description"
          content="Contacter nous pour plus d'information à propos de la mobilité internationale au sein de l'école 3iL">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <h4>Contact Page</h4>
        <div class="form-style">
            <form method="post" class="myform" action="/Form/contact_me.php">
                <input type="text" name="name" placeholder="Your Name" required><br>
                <input type="email" name="email" placeholder="Your Email" required><br>
                <textarea rows="4" cols="20" name="message" placeholder="Your Message"></textarea><br>
                <input type="submit" name="send" value="Send"> <span class="output_message"></span>
            </form>
        </div>
    </div><!--container-->

    <?php include('Defaut/menu.phtml'); ?>

    <?php include('Defaut/footer.phtml'); ?>

    <script src="../js/contact.js"></script>
    <script src="../js/alert-box.js"></script>

</div><!--end wrapper-->

</body>
</html>