<html lang="fr" xmlns="http://www.w3.org/1999/html">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity | Destinations</title>
    <meta name="description"
          content="Liste des destinations pour le choix de la mobilité internationnale au sein de l'école 3iL">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <h4>Liste des destinations possibles</h4>
        <div class="searchArea">
            <form id="searchDestination" action="../controleurs/ControllerDestinations.php" method="POST">
                <input type="text" name="search" class="searchTerm"
                       placeholder="Rechercher une université, un mot-clé..."/>
                <br/>
                <label for="spokenLanguage">Langue : </label>
                <?php
                foreach ($listeLangue as $rowLangue) {
                    echo "<input type='checkbox' name='lang[]' value='" . $rowLangue["idLangue"] . "' />" . $rowLangue["libelleLangue"];
                } ?>
                <br/>
                <label for="pays">Pays : </label>
                <select name="pays" id="pays">
                    <option value="Tous">Tous</option>
                    <?php

                    foreach ($listePays as $rowPays) {
                        echo "<option value='" . $rowPays["pays"] . "'>" . $rowPays["pays"] . "</option>";
                    } ?>
                </select><br/>
                <button type="submit" class="searchButton" onclick="rechercheDetaillee()">
                    Lancer la recherche
                </button>
            </form>
        </div>
        <hr/>
        <div class="resultDestination">
            <?php foreach ($listeDestinations as $rowDesti) {
            // mise en forme CSS : fsDefault puis une couleur spécifique pour chaque pays
            echo "<fieldset class='fsDefault " . $rowDesti["pays"] . "'>
                        <legend>" . $rowDesti["pays"] . "</legend>";
            ?>

            <!-- logo aligné intérieur gauche -->
            <div class="logoRow">
                <img src="../medias/images/logo/<?= $rowDesti["idDestination"] ?>.png" alt=<?= $rowDesti["nomEcole"] ?>/>
            </div>
            <!-- premiere partie du texte alignée intérieur haut droite -->
            <div class="topTextRow"><?= $rowDesti["nomEcole"] ?></div>
            <!-- seconde partie intérieur bas droite -->
            <div class="bottomTextRow">
                <?php echo  $rowDesti["pays"] . "<br /> Durée  : " . $rowDesti["duree"] . " semaines <br/>" . $rowDesti["descriptif"]; ?>

            <?php
                    echo "</div></fieldset><br />";
            }?>


    </div>
</div><!--container-->

<?php include('Defaut/menu.phtml'); ?>

<?php include('Defaut/footer.phtml'); ?>
</div><!--end wrapper-->

</body>
</html>