<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity | Destination</title>
    <meta name="description"
          content="Caractéristiques de la ville.">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <?php
            if (!empty($_GET["desti"])) {
                echo $_GET["desti"];
            }
        ?>
        <!-- TODO vérifier validité de l'argument dans l'url -->
    </div><!--container-->

    <?php include('Defaut/menu.phtml'); ?>

    <?php include('Defaut/footer.phtml'); ?>

    <script src="../js/contact.js"></script>
    <script src="../js/alert-box.js"></script>

</div><!--end wrapper-->

</body>
</html>