<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity | Destination</title>
    <meta name="description"
          content="Caractéristiques de la ville.">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">

        <!-- Argument URL vérifié dans contrôleur : 404 si ERREUR -->
        <h4><?=$infosDesti["nomEcole"]?></h4>
        <br />
        <h5><?=$infosDesti["pays"]?></h5>
        <br /><br />

        <div id="descrDesti">
            <span id="txtDescr"><!-- aligné à gauche -->
                <p><?=$infosDesti["descriptif"]?></p>
            </span><!--txtDescr-->
            <span id="resume"><!-- aligné à droite -->
                <img id="imgResume" src="../medias/images/logo/<?=$infosDesti["idDestination"]?>.png" alt="<?=$infosDesti["nomEcole"]?>">
                <br />
                <table id="tbResume">
                    <tbody>
                    <tr>
                        <th scope="row">Langue(s) parlée(s)</th>
                        <td><?php foreach($spokenLang as $aLangage) { echo $aLangage["libelleLangue"]." "; }?></td>
                    </tr>
                    <tr>
                        <th scope="row">Durée</th>
                        <td><?=$infosDesti["duree"]?></td>
                    </tr>
                    <tr>
                        <th scope="row">Choix obligatoire</th>
                        <td><?php echo ($infosDesti["estObligatoire"]==1)?"Oui":"Non"?></td>
                    </tr>
                    </tbody>
                </table>
            </span><!--resume-->
        </div><!--descrDesti-->
        <br /> <br />
        <div id="temoignages">
            <h4>Témoignages</h4>
            <!-- parcours des témoignages -->
            <?php
            $cpt = 0; // compteur affichage des thèmes
            if (is_null($temoignageDesti[0]["idTemoignage"])) {
                // aucun témoignage
            ?>
                <div class="rowTemoignage"><p>Il n'y a pas encore de témoignage pour cette destination.</p><br /></div>
                <?php
            } else {// if
                foreach ($temoignageDesti as $rowTemoignage) { ?>
                    <div class="rowTemoignage">

                        <p> De <b><?=$rowTemoignage["nomVoyageur"]?></b>, le <?php echo date_format(new DateTime($rowTemoignage["dateTemoignage"]),'d/m/Y');?> : </p>                       
                        <table id="tbNotes">
                            <tbody>
                            <?php foreach ($infosTemoignage as $rowInfosTemoignage) { ?>
                                <tr>
                                    <th scope="row"><a href="#<?=$rowInfosTemoignage["idInfos"]?>"><?=$libellesTheme[$cpt]["nomTheme"]?></a></th>
                                    <td><?=$rowInfosTemoignage["note"]?></td>
                                </tr>
                            <?php $cpt++; } ?>
                             <tr>
                                <th class="libNoteMoyenne" scope="row">Note moyenne</th>
                                <td class="noteMoyenne"><?=round($rowTemoignage["moyenne"],1)?></td><td class="sansMEF">/10</td>
                            </tbody>
                        </table>
                        <br />
                        <!-- Détail pour chaque thématique -->
                <?php $cpt = 0; foreach ($infosTemoignage as $rowInfosTemoignage) { ?>
                    <div class="rowTheme">
                        <table style="table-layout: fixed;">
                            <tbody>
                            <tr class="rowThemeDetail">
                                <td class="cellNoteTheme" rowspan="2"><?=$rowInfosTemoignage["note"]?></td>
                                <td class="cellTitleTheme" id="<?=$rowInfosTemoignage["idInfos"]?>"><?=$libellesTheme[$cpt]["nomTheme"]?></td>
                            </tr>
                            <tr class="rowThemeTxtDescr">
                                <td class="cellTextTheme"><?=$rowInfosTemoignage["texteDescriptif"]?></td>
                            </tr>
                            </tbody>
                        </table>
                    </div><!--rowTheme-->
                <?php $cpt++; }?>

                <?php
                } // for
            } // if-else?>
                </div> <!--rowTemoignage-->
        </div><!-- temoignages -->


    </div><!--container-->

    <?php include('Defaut/footer.phtml'); ?>

    <script src="../js/contact.js"></script>
    <script src="../js/alert-box.js"></script>

</div><!--end wrapper-->

</body>
</html>