<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity</title>
    <meta name="description" content="Projet de site web sur le choix de la mobilité internationnale à l'école 3iL">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <div class="slider-content slider-display-container">
        <?php
        $xml = simplexml_load_file('medias/infoSlider.xml');
        foreach ($xml as $destination) {  ?>
            <div class="slider-display-container mySlides">
                <div class="desti">
                    <img src=<?=$destination->photo; ?> style="width:100%">
                    <div class="descrImage"><?=$destination->description; ?></div>
                </div>
                <div class="slider-display-middle-bottom slider-large slider-container slider-padding-16 slider-black">
                    <?=$destination->nom; ?>
                </div>
            </div>
        <?php } ?>
            <button class="slider-button slider-black slider-display-left" onclick="plusDivs(-1)">&#10094;</button>
            <button class="slider-button slider-black slider-display-right" onclick="plusDivs(1)">&#10095;</button>
        </div>
        <br /><br />
        <!-- Texte présentation -->
        <div class="presentationTxt">
            <p>Bienvenue sur le site de mobilité internationale de 3iL. <br />
            Ce site est principalement destiné aux étudiants 3iL Rodez et Limoges dans le but de les aider à faire leur
            choix parmi un ensemble de destinations qui leur sont proposées en troisième année. <br />
            Ce semestre à l'étranger leur permettra de valider leur diplôme d'ingénieur et surtout une expérience inoubliable ! <br />
            C'est pourquoi, l'ordonancement de leur voeux est primordial.<br />
            Des témoignages d'autres étudiants sont également disponibles afin de les renseigner sur certaines destinations.
            </p>
        </div>

    </div><!--container-->


    <?php include('Defaut/footer.phtml'); ?>

    <script src="../js/slider.js"></script>
</div><!--end wrapper-->

</body>
</html>