<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>Internationnal Mo3iLity</title>
    <meta name="description" content="Projet de site web sur le choix de la mobilité internationnale à l'école 3iL">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <header>
        <h1 class="logo"><a href="">International Mo3iLity</a></h1>
        <a class="to_nav" href="#primary_nav">Menu</a>
    </header>

    <!--     Contenu de la page -->
    <div class="container">
        <h4>Basic Page</h4>
        <p>Work In Progress</p>
    </div><!--container-->

    <nav id="primary_nav">
        <ul>
            <li><a href="">Accueil</a></li>
            <li><a href="">Destinations</a></li>
            <li><a href="">Faire ses voeux</a></li>
            <li><a href="">Témoignages</a></li>
            <li><a href="">Contact</a></li>
            <li class="top"><a href="#home">Top</a></li>
        </ul>
    </nav><!--end primary_nav-->

    <footer>
        <p>Copyright &copy; <?php echo date("Y"); ?> - Florian Louargant & Pierre Frugere.</p>
    </footer>

</div><!--end wrapper-->

</body>
</html>