<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity</title>
    <meta name="description" content="Projet de site web sur le choix de la mobilité internationnale à l'école 3iL">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <div class="slider-content slider-display-container">
            <div class="slider-display-container mySlides">
                <img src="../medias/images/ottawa.jpg" style="width:100%">
                <div class="slider-display-middle-bottom slider-large slider-container slider-padding-16 slider-black">
                    Ottawa
                </div>
            </div>
            <div class="slider-display-container mySlides">
                <img src="../medias/images/saguenay.jpg" style="width:100%">
                <div class="slider-display-middle-bottom slider-large slider-container slider-padding-16 slider-black">
                    Saguenay
                </div>
            </div>
            <div class="slider-display-container mySlides">
                <img src="../medias/images/sofia.jpg" style="width:100%">
                <div class="slider-display-middle-bottom slider-large slider-container slider-padding-16 slider-black">
                    Sofia
                </div>
            </div>

            <button class="slider-button slider-black slider-display-left" onclick="plusDivs(-1)">&#10094;</button>
            <button class="slider-button slider-black slider-display-right" onclick="plusDivs(1)">&#10095;</button>
        </div>
        <h4>Basic Page</h4>
        <p>Work In Progress</p>
    </div><!--container-->

    <?php include('Defaut/menu.html'); ?>

    <?php include('Defaut/footer.phtml'); ?>

    <script src="../js/slider.js"></script>
</div><!--end wrapper-->

</body>
</html>