<html lang="fr" xmlns="http://www.w3.org/1999/html">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity | Destinations</title>
    <meta name="description"
          content="Liste des destinations pour le choix de la mobilité internationnale au sein de l'école 3iL">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <h2>Liste des destinations possibles</h2>
        <br />
        <p><center>Renseignez différents critères ci-dessous afin d'affiner votre recherche.</center></p>
        <div id="searchArea">
            <form id="searchDestination" action="../controleurs/ControllerListeDestinations.php" method="POST">
                <div>
                    <input type="text" name="search" class="searchTerm" placeholder="Rechercher une université, un mot-clé..."/>
                </div>
                <br/>
                <div>
                    <label for="spokenLanguage">Langue : </label>
                    <?php
                    foreach ($listeLangue as $rowLangue) {
                        echo "<label class='cb_container'>". $rowLangue["libelleLangue"];
                        echo "<input type='checkbox' name='lang[]' value='" . $rowLangue["idLangue"] . "' /><span class='cb_checkmark'></span>" ;
                        echo "</label>";
                    } ?>
                </div>
                <br/>
                <div>
                    <label for="pays" style="vertical-align: middle;">Pays : </label>
                    <span class="cbb_pays">
                        <select name="pays">
                            <option value="Tous">Tous</option>
                            <?php

                            foreach ($listePays as $rowPays) {
                                echo "<option value='" . $rowPays["pays"] . "'>" . $rowPays["pays"] . "</option>";
                            } ?>
                        </select>
                    </span>
                </div>
                <br/>
                <div>
                    <button type="submit" class="btDefault" onclick="rechercheDetaillee()">Lancer la recherche</button>
                </div>
            </form>
            <br />
        </div>
        <div class="resultDestination">
            <?php foreach ($listeDestinations as $rowDesti) {
            // mise en forme CSS : fsDefault puis une couleur spécifique pour chaque pays
            echo "<fieldset class='fsDefault " . $rowDesti["pays"] . "'>
                        <legend><h2>" . $rowDesti["pays"] . "</h2></legend>";
            ?>

            
            <div class="fscontent">
                <!-- logo aligné intérieur gauche -->
                <span class="logoRow">
                    <a href="destination.php?desti=<?= $rowDesti["idDestination"] ?>">
                        <img src="../medias/images/logo/<?= $rowDesti["idDestination"] ?>.png" alt=<?= $rowDesti["nomEcole"] ?>/>
                    </a>
                </span>
                <!-- premiere partie du texte alignée intérieur haut droite -->
                <div class="rightContent">
                <div class="topTextRow"><a href="destination.php?desti=<?= $rowDesti["idDestination"] ?>"><?= $rowDesti["nomEcole"] ?></a></div>
                <input type="button" class="btn-voirDetailDesti" onclick="location.href='destination.php?desti=<?= $rowDesti["idDestination"] ?>';" value="Voir" />
                <!-- seconde partie intérieur bas droite -->
                <div class="bottomTextRow">
                    <?php echo  "<br /><p class='txt-oblic'>Pays : " . $rowDesti["pays"] . "</p><p class='txt-oblic'>Durée  : " . $rowDesti["duree"] . " semaines </p>" . 
                    "<br /><br/>" . $rowDesti["descriptif"]; ?>

                <?php
                        echo "</div></div></fieldset><br />";
                }?>



    </div>


</div><!--container-->

<?php include('Defaut/footer.phtml'); ?>
</div><!--end wrapper-->

</body>
</html>