<html lang="fr">
<head>

    <meta charset="utf-8">
    <title>International Mo3iLity | Voeux</title>
    <meta name="description" content="Choisissez vos voeux pour la mobilité internationnale au sien de l'école 3iL">
    <meta name="author" content="Florian Louargant & Pierre Frugere">

    <!-- Le meta magique pour les appareils mobiles :)-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Font–––––––– -->
    <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

    <!--css-->
    <link rel="stylesheet" href="../css/style.css">

    <!-- js -->
    <script src="../js/jquery-3.3.1.min.js"></script>
    <script src="../js/jquery-ui.min.js"></script>

    <!--    TODO - voir l'utilité réellement-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Favicons-->
    <link rel="icon" type="image/png" href="../medias/images/favicon.png">

</head>
<body id="home">

<div class="wrapper">

    <?php include('Defaut/header.html'); ?>

    <!--     Contenu de la page -->
    <div class="container">
        <h4>Voeux Page</h4> <br />

        <form action="processVoeux.php" method="post" id="voeux-form">
            <label for="school">Ecole : </label>
            <input type="radio" id="groupRodez" name="group" value="Rodez" onchange="afficherGroupe();" checked />
            <label for="groupRodez">3iL Rodez</label>
            <input type="radio" id="groupLimoges" name="group" value="Limoges" onchange="afficherGroupe();"/>
            <label for="groupLimoges">3iL Limoges</label>
            <br />

            <label for="lastname">Nom : </label>
            <input type="text" id="lastname"/><br />
            <label for="firstname">Prénom : </label>
            <input type="text" id="firstname"/><br />
            <label for="firstname">Année scolaire : </label>
            <select name="schoolYear" id="schoolYear">
                <option value="lastYear"><?php $current= date("Y"); echo $current-2 . " - " . ($current+1);  ?></option>
                <option value="currentYear"><?php echo $current-1 . " - " . ($current+2); ?></option>
                <option value="nextYear"><?php echo $current . " - " . ($current+3); ?></option>
            </select><br />
            <!-- demande du groupe uniquement pour 3iL Rodez -->
            <div id="groupe3iL">
                <label for="group">Groupe : </label>
                <select name="group" id="group">
                    <option value="groupA">A</option>
                    <option value="groupB">B</option>
                </select><br />
            </div>
            <label for="listVoeux">Voeux ordonnés : </label>
            <p>Seuls les sept premiers voeux seront retenus. Ils doivent contenir les destinations partenaires avec l'école 3iL.</p>

            <!-- tableau drag & drop -->
            <table id="sort" class="grid" title="ListeDesVoeux">
                <thead>
                    <tr><th class="index">No.</th><th>Lieu</th><th>Ecole</th><th>Durée (semaines)</th></tr>
                </thead>
                <tbody>
                <?php
                $index=1;
                $NB_MAX_DESTI = 7;
                foreach ($listeDestinations as $rowUniversity) {
                    // affichage différents pour les 7 premiers choix
                    if ($index <= $NB_MAX_DESTI) {
                        // destination obligatoire --> affichage différent
                        if ($rowUniversity["estObligatoire"] == 1) {
                            echo "<tr class='rowToSelect obligatoire' style='background-color: #4CAF50;'>
                                <td class='index'>" . $index . "</td>
                                <td>" . $rowUniversity["pays"] . "</td>
                                <td>" . $rowUniversity["nomEcole"] . "</td>
                                <td>" . $rowUniversity["duree"] . "</td>
                              </tr>";
                        } else {
                            echo "<tr class='rowToSelect nonObligatoire'>
                                <td class='index'>" . $index . "</td>
                                <td>" . $rowUniversity["pays"] . "</td>
                                <td>" . $rowUniversity["nomEcole"] . "</td>
                                <td>" . $rowUniversity["duree"] . "</td>
                              </tr>";
                        }

                    } else {
                        // destination obligatoire --> affichage différent
                        if ($rowUniversity["estObligatoire"] == 1) {
                            echo "<tr class='obligatoire' style='background-color: #4CAF50;'>
                                <td class='index'>" . $index . "</td>
                                <td>" . $rowUniversity["pays"] . "</td>
                                <td>" . $rowUniversity["nomEcole"] . "</td>
                                <td>" . $rowUniversity["duree"] . "</td>
                              </tr>";
                        } else {
                            echo "<tr class='nonObligatoire'>
                                <td class='index'>" . $index . "</td>
                                <td>" . $rowUniversity["pays"] . "</td>
                                <td>" . $rowUniversity["nomEcole"] . "</td>
                                <td>" . $rowUniversity["duree"] . "</td>
                              </tr>";
                        }
                    }
                    $index++;
                }
                ?>
                </tbody>
            </table>
            <br />
            <input type="submit" id="submit" value="Valider"/>
            <!-- TODO action d'envoi de formulaire (ne pas récupérer le groupe si l'élève vient de 3iL Limoges) -->
            </p>
        </form>

        <p>Work In Progress</p>
    </div><!--container-->

    <?php include('Defaut/menu.phtml'); ?>

    <?php include('Defaut/footer.phtml'); ?>

    <script src="../js/voeuxArray.js"></script>
</div><!--end wrapper-->

</body>
</html>